server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  ai:
    openai:
      api-key: ${OPEN_AI_KEY:AIzaSyAGvATwDdavDTN-7fk6lsv2mZroP94cJaM}
      chat:
        base-url: ${OPEN_AI_URL:https://generativelanguage.googleapis.com}
        completions-path: ${OPEN_AI_PATH:/v1beta/openai/chat/completions}
        options:
          model: ${OPEN_AI_MODEL:gemini-2.0-flash}
  application:
    name: roomie-connect-be
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/roomie}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ISSUER_URI:http://13.115.95.121:8001/realms/group1}
          jwk-set-uri: ${JWK_SET_URL:http://13.115.95.121:8001/realms/group1/protocol/openid-connect/certs}
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID:roomie-connect_app}
            client-secret: ${CLIENT_SECRET:rY4wgcH11RxwNSDlQuQk6GYtcpRRuJ0F}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            redirect-uri: ${REDIRECT_URI:http://13.115.95.121:3000/*}
        provider:
          keycloak:
            authorization-uri: ${AUTHORIZATION_URI:http://13.115.95.121:8001/realms/group1/protocol/openid-connect/auth}
            token-uri: ${TOKEN_URI:http://13.115.95.121:8001/realms/group1/protocol/openid-connect/token}
            user-info-uri: ${USER_INFO_URI:http://13.115.95.121:8001/realms/group1/protocol/openid-connect/userinfo}
            jwk-set-uri: ${JWK_SET_URI:http://13.115.95.121:8001/realms/group1/protocol/openid-connect/certs}
            user-name-attribute: preferred_username

minio:
  config:
    url: ${MINIO_CONFIG_URL:http://localhost:9000}
    username: ${MINIO_ROOT_USER:minioadmin}
    password: ${MINIO_ROOT_PASSWORD:minioadmin}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

idp:
  client:
    id: ${CLIENT_ID:roomie-connect_app}
    secret: ${CLIENT_SECRET:rY4wgcH11RxwNSDlQuQk6GYtcpRRuJ0F}
  token:
    endpoint: ${TOKEN_URI:http://13.115.95.121:8001}
